version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD:-YourStrong!Passw0rd}
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    command: start-dev

  db-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db-server
    platform: ${DB_PLATFORM:-}
    environment:
      SA_PASSWORD: ${DB_PASSWORD:-YourStrong!Passw0rd}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - task-network
    restart: always
    volumes:
      - taskmanager_sqlserver_data_dev:/var/opt/mssql 

  rabbitmq:
    image: rabbitmq:3-management 
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672" 
      - "15672:15672" 
    environment:
      - RABBITMQ_DEFAULT_USER=${RMQ_USER:-admin}
      - RABBITMQ_DEFAULT_PASS=${RMQ_PASSWORD:-YourStrong!Passw0rd}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  task-service:
    build:
      context: ./backend
      dockerfile: ./Services/TaskService/Dockerfile
      target: debug 
    container_name: task-service
    depends_on:
      - db-server
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__TaskDb=Server=db-server;Database=TaskDb;User Id=sa;Password=${DB_PASSWORD:-YourStrong!Passw0rd};TrustServerCertificate=True;
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RMQ_USER:-admin}
      - RABBITMQ_PASS=${RMQ_PASSWORD:-YourStrong!Passw0rd}
    ports:
      - "5001:8080"
    volumes:
      - ./backend/Services/TaskService:/src  
    networks:
      - task-network

  user-service:
    build:
      context: ./backend
      dockerfile: ./Services/UserService/Dockerfile
      target: debug 
    container_name: user-service
    depends_on:
      - db-server
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__UserDb=Server=db-server;Database=UserDB;User Id=sa;Password=${DB_PASSWORD:-YourStrong!Passw0rd};TrustServerCertificate=True;
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RMQ_USER:-admin}
      - RABBITMQ_PASS=${RMQ_PASSWORD:-YourStrong!Passw0rd}
    ports:
      - "5002:8080"
    volumes:
      - ./backend/Services/UserService:/src  
    networks:
      - task-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: debug
    container_name: frontend
    ports:
      - "3000:5173"
      - "9229:9229"  
    volumes:
      - ./frontend:/app
      - /app/node_modules 
    environment:
      - NODE_ENV=development
    networks:
      - task-network

networks:
  task-network:
    driver: bridge

volumes:
  taskmanager_sqlserver_data_dev:
  keycloak_data:
  rabbitmq_data:
