version: "3.8"

services:  
  db-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db-server
    platform: ${DB_PLATFORM:-}
    environment:
      SA_PASSWORD: "${DB_PASSWORD:-YourStrong!Passw0rd}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - task-network
    restart: always
    volumes:
      - taskmanager_sqlserver_data:/var/opt/mssql

  task-service:
    build:
      context: ./Services/TaskService
      dockerfile: Dockerfile
    container_name: task-service
    depends_on:
      - db-server
    environment:
      - ConnectionStrings__TaskDb=Server=db-server;Database=TaskDb;User Id=sa;Password=${DB_PASSWORD:-YourStrong!Passw0rd};
    ports:
      - "5001:8080"
    networks:
      - task-network
    restart: always

  user-service:
    build:
      context: ./Services/UserService
      dockerfile: Dockerfile
    container_name: user-service
    depends_on:
      - db-server
    environment:
      - ConnectionStrings__UserDb=Server=db-server;Database=UserDB;User Id=sa;Password=${DB_PASSWORD:-YourStrong!Passw0rd};
    ports:
      - "5002:8080"
    networks:
      - task-network
    restart: always

networks:
  task-network:
    name: task-network  # <-- This ensures frontend can connect later
    external: false

volumes:
  taskmanager_sqlserver_data: